// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB1N6nXAlMgdsdZhVWd2yQbRx7vwXTnGE',
    appId: '1:370580773058:web:4e2fa930d3a3ec57cfc35b',
    messagingSenderId: '370580773058',
    projectId: 'notify-app-8ea8b',
    authDomain: 'notify-app-8ea8b.firebaseapp.com',
    storageBucket: 'notify-app-8ea8b.appspot.com',
    measurementId: 'G-2ZHSP2QTH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvrBTHrrcY0cxuvpzUOZAOUFlRl5GXPjY',
    appId: '1:370580773058:android:f9760b75973ccf33cfc35b',
    messagingSenderId: '370580773058',
    projectId: 'notify-app-8ea8b',
    storageBucket: 'notify-app-8ea8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqT7fhXqDs4AiJL5arQ3JVy3ZQK9OuTdI',
    appId: '1:370580773058:ios:73ec842116bf8cc7cfc35b',
    messagingSenderId: '370580773058',
    projectId: 'notify-app-8ea8b',
    storageBucket: 'notify-app-8ea8b.appspot.com',
    iosBundleId: 'com.example.notf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqT7fhXqDs4AiJL5arQ3JVy3ZQK9OuTdI',
    appId: '1:370580773058:ios:b9a66d3102728f2ccfc35b',
    messagingSenderId: '370580773058',
    projectId: 'notify-app-8ea8b',
    storageBucket: 'notify-app-8ea8b.appspot.com',
    iosBundleId: 'com.example.notf.RunnerTests',
  );
}
